apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-music-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/Samsung4TB/navidrome/music
    type: Directory
