services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    group_add:
      - "994"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /Docker/docker_volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
