---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - JELLYFIN_PublishedServerUrl=http://192.168.2.150 #optional
    volumes:
      - /Docker/docker_volumes/arr/jellyfin:/config
      - /mnt/Samsung4TB/Plex/TV Shows:/data/tvshows
      - /mnt/Samsung4TB/Plex/Movies:/data/movies

      - /usr/share/fonts:/usr/share/fonts:ro
      - /etc/fonts:/etc/fonts:ro
    ports:
      - 8096:8096
    restart: unless-stopped
