apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/emsmw/minos.git
    targetRevision: main
    path: k8s-manifests/navidrome
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
